// Datos de ejemplo para la aplicación

export const mockIncidencias = [
  {
    id: 1,
    titulo: "Error en el sistema de login",
    descripcion: "Los usuarios no pueden iniciar sesión en la plataforma desde ayer.",
    estado: "Abierta",
    prioridad: "Alta",
    fechaCreacion: "2025-05-10",
    creador: "usuario@example.com",
    tecnico: "tecnico@example.com",
    gestor: "gestor@example.com",
  },
  {
    id: 2,
    titulo: "Problema con la impresora de la oficina",
    descripcion: "La impresora del departamento de contabilidad no funciona correctamente.",
    estado: "En proceso",
    prioridad: "Media",
    fechaCreacion: "2025-05-12",
    creador: "usuario@example.com",
    tecnico: "tecnico@example.com",
    gestor: "gestor@example.com",
  },
  {
    id: 3,
    titulo: "Solicitud de nuevo equipo",
    descripcion: "Necesito un nuevo ordenador para el nuevo empleado que se incorpora la próxima semana.",
    estado: "Cerrada",
    prioridad: "Baja",
    fechaCreacion: "2025-05-05",
    creador: "gestor@example.com",
    tecnico: "tecnico@example.com",
    gestor: "gestor@example.com",
    resolucion: "Se ha asignado un nuevo equipo al empleado.",
  },
  {
    id: 4,
    titulo: "Actualización de software pendiente",
    descripcion: "Es necesario actualizar el software de gestión a la última versión.",
    estado: "Abierta",
    prioridad: "Media",
    fechaCreacion: "2025-05-14",
    creador: "admin@example.com",
    tecnico: null,
    gestor: "gestor@example.com",
  },
  {
    id: 5,
    titulo: "Fallo en la conexión a internet",
    descripcion: "La conexión a internet es intermitente en toda la oficina.",
    estado: "En proceso",
    prioridad: "Alta",
    fechaCreacion: "2025-05-15",
    creador: "usuario@example.com",
    tecnico: "tecnico@example.com",
    gestor: "gestor@example.com",
  },
  {
    id: 6,
    titulo: "Problema con el correo electrónico",
    descripcion: "No puedo enviar correos electrónicos desde mi cuenta corporativa.",
    estado: "Abierta",
    prioridad: "Alta",
    fechaCreacion: "2025-05-16",
    creador: "admin@example.com",
    tecnico: null,
    gestor: null,
  },
  {
    id: 7,
    titulo: "Solicitud de acceso a la base de datos",
    descripcion: "Necesito acceso a la base de datos de clientes para realizar un informe.",
    estado: "Cerrada",
    prioridad: "Baja",
    fechaCreacion: "2025-05-01",
    creador: "gestor@example.com",
    tecnico: "tecnico@example.com",
    gestor: "gestor@example.com",
    resolucion: "Se ha concedido el acceso solicitado.",
  },
  {
    id: 8,
    titulo: "Error en la aplicación de facturación",
    descripcion: "La aplicación de facturación muestra un error al intentar generar facturas.",
    estado: "En proceso",
    prioridad: "Media",
    fechaCreacion: "2025-05-13",
    creador: "usuario@example.com",
    tecnico: "tecnico@example.com",
    gestor: "gestor@example.com",
  },
]

export const mockUsuarios = [
  {
    id: 1,
    nombre: "Admin",
    apellido: "Sistema",
    email: "admin@example.com",
    telefono: "600123456",
    tipo: "Administrador",
  },
  {
    id: 2,
    nombre: "Técnico",
    apellido: "Soporte",
    email: "tecnico@example.com",
    telefono: "600234567",
    tipo: "Técnico",
  },
  {
    id: 3,
    nombre: "Gestor",
    apellido: "Proyectos",
    email: "gestor@example.com",
    telefono: "600345678",
    tipo: "Gestor",
  },
  {
    id: 4,
    nombre: "Usuario",
    apellido: "Final",
    email: "usuario@example.com",
    telefono: "600456789",
    tipo: "Usuario",
  },
  {
    id: 5,
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@example.com",
    telefono: "600567890",
    tipo: "Técnico",
  },
  {
    id: 6,
    nombre: "Carlos",
    apellido: "López",
    email: "carlos.lopez@example.com",
    telefono: "600678901",
    tipo: "Gestor",
  },
  {
    id: 7,
    nombre: "Laura",
    apellido: "García",
    email: "laura.garcia@example.com",
    telefono: "600789012",
    tipo: "Usuario",
  },
]

export const mockTecnicos = [
  {
    id: 2,
    nombre: "Técnico",
    apellido: "Soporte",
    email: "tecnico@example.com",
  },
  {
    id: 5,
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@example.com",
  },
]

export const mockTiposUsuario = ["Administrador", "Técnico", "Gestor", "Usuario"]
